services:
  gradle_build:
    build: ./
    restart: "no"
    volumes:
      - tg-jar:/app/app/build/libs

  tg_bot:
    build: ./app
    container_name: telegram_bot
    restart: on-failure:3
    depends_on:
      gradle_build:
        condition: service_completed_successfully
    volumes:
      - tg-jar:/libs

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    restart: on-failure:3
    ports:
      - "4444:4444"
    depends_on:
      tg_bot:
        condition: service_started

#  redis:
#    build: ./redis
#    container_name: redis
#    ports:
#      - "6379:6379"
#    depends_on:
#      tg_bot:
#        condition: service_started

#  db:
#    image: postgres
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: mydb

volumes:
  tg-jar: