services:
  gradle_build:
    build: ./
    restart: "no"
    volumes:
      - tg-jar:/app/app/build/libs

  tg_bot:
    build: ./app
    restart: "no"
    depends_on:
      gradle_build:
        condition: service_completed_successfully
    volumes:
      - tg-jar:/libs

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    ports:
      - "4444:4444"
    depends_on:
      tg_bot:
        condition: service_completed_successfully

volumes:
  tg-jar: