version: "3"

services:
  gradle_build:
    build: ./
    restart: always
    volumes:
      - tg-jar:/app/app/build/libs

  tg_bot:
    build: ./app
    restart: always
    depends_on:
      gradle_build:
        condition: service_completed_successfully
    volumes:
      - tg-jar:/libs

volumes:
  tg-jar: