/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package telegram.bot;

public class Bot {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Bot().getGreeting());
    }
}
