/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package telegram.bot;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class BotTest {
    @Test void appHasAGreeting() {
        Main classUnderTest = new Main();

    }
}
